language: swift
osx_image: xcode11.3
xcode_project: Negative.xcodeproj # path to your xcodeproj folder
xcode_scheme: Negative
xcode_destination: "platform:iOS Simulator, OS:13.3, name:iPhone 11 Pro Max"
