language:
  - swift
osx_image: xcode11.3
script:
  - xcodebuild -scheme Negative -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.3' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
